### ISSUE TITLE
Fail to filter with log level in CI environment

### ISSUE THREAD

**Issue by lujiajing1126** [khmarbaise/maven-it-extension#170]
**Describe the bug**
When running in gitlab-ci environment, the stdout log will contain line number before log level,
so the filtering of logs with level will fail

**To Reproduce**
Run in gitlab-ci

**Current behavior**
Fail to assert with something like `assertThat(result).out().error().contains("fail to run task myBatisCheck");`

**Expected behavior**
Run w/o issues

**Screenshots**

I print the `stdout.log` in the ci test with `log:` prefix.

![image](https://user-images.githubusercontent.com/2568208/100405081-d961dc00-309d-11eb-8c3c-b72754903566.png)

**The used versions**
0.9.0

 - Maven: Meven 3.6.3
 - JDK: openjdk-8
 - IDE: not applicable

**Comment by khmarbaise** [comment]
Can you please make a full working example of that.... Also I see that it looks like the slf4j seemed to be configured ...

**Comment by lujiajing1126** [comment]
> Can you please make a full working example of that.... Also I see that it looks like the slf4j seemed to be configured ...

Sure. I have made [an example repository](https://github.com/lujiajing1126/maven-it-extension-issue170). I have tested with several well-known CI services,

- Gitlab-CI: https://gitlab.com/lujiajing1126/maven-it-extension-issue170/-/jobs/887324264
- Circle CI
- Azure Pipelines
- Github Actions

The reports of last three tests can be found here https://github.com/lujiajing1126/maven-it-extension-issue170/actions?query=workflow%3A%22MavenIT+CI%22+branch%3Amain

The only failure is the first one as you can see from the logs.

**Comment by khmarbaise** [comment]
So it took me some time to understand where the real issue is located and the final problem is simply the configuration in your Gitlab pipeline:

* https://gitlab.com/lujiajing1126/maven-it-extension-issue170/-/commit/cdd27f959eb3213a3948b53db88d0a36bbfd19e2

The configuration in your GitLab pipeline:
```
MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository 
  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN 
  -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
```
The real issue is the configuration part: `-Dorg.slf4j.simpleLogger.showDateTime=true`

which prints out ([excerpts from the docs](http://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html)): 
> milliseconds, thread name, the level, logger name, and the message followed by the line separator for the host. In log4j terms it amounts to the "%r [%t] %level %logger - %m%n" pattern.

which is unrelated to line numbers etc. 

Some suggestions to help here:

* If you want to suppress the transfer outputs use simply `--no-transfer-progress` (See release notes [Maven 3.6.1+](https://maven.apache.org/docs/3.6.1/release-notes.html)) it's easier and simpler than configuration via `MAVEN_OPTS` and `Slf4jMavenTransferListener`... 

* If you change the logging format than you can of course not work anymore with the usual:
```
assertThat(result).out().error().contains("fail to run task myBatisCheck");
```
you have to change to:
```
assertThat(result).out().plain().<Do what is needed>....contains("fail to run task myBatisCheck");
```
Changing the output format with something time based makes writing tests in general more or less impossible or you have to circumvent that via the above mentioned `.out().plain()..` where you have access the log output without any filters etc. and you can do what ever you like / need.

* The configuration for the TLS part `-Dhttps.protocols=TLSv1.2` is only needed for JDK7 not for JDK 8 ...because JDK 7 defaults to `TLSv1.1` which is not supported anymore by central repository

Another hint about your Git Lab configuration or to be accurate the comments in it: The `.mvn/maven.config` has been started in Maven 3.3.1 see the release notes https://maven.apache.org/docs/3.3.1/release-notes.html and not in 3.3.0 cause this version has never been become published.

**Comment by lujiajing1126** [comment]
I appreciate your elaboration. I've removed the `slf4j` related configurations and it works well now.

I really never dig very deep into maven, just use it as a build tool. Thanks again for your helpful tips.

**Comment by khmarbaise** [comment]
Glad that I could help. Thanks for the feedback.
