### ISSUE TITLE
Enable debugging of plugin while running integration tests

### ISSUE THREAD

**Issue by arunkjn** [khmarbaise/maven-it-extension#180]
**Is your feature request related to a problem? Please describe.**
I am not able to set breakpoints in the plugin code when running integration tests.

**Describe the solution you'd like**
While running the integration tests in debug mode, it would be nice to be able to break on the breakpoints within the plugin code. Normally this would happen when we run maven with `mvnDebug` on the host application which is using the plugin, and then attaching a remote debugger to it.

**Comment by scholzb-hb** [comment]
We have the same feature request. Our current workaround (on Windows):

1. Create a copy of your local Maven installation with suffix "-debug", e.g.:
`C:\maven\apache-maven-3.6.0-debug`
2. Open the file "C:\maven\apache-maven-3.6.0-debug\bin\mvn.cmd" and add the following lines at the top:
```
setlocal
set MAVEN_DEBUG_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000
```
3. In the IDE, run your integration test(s) with the following system property:
`maven.home=C:\maven\apache-maven-3.6.0-debug`
4. In the IDE, connect the debugger to the remote JVM at port 8000

The last step must be repeated for each integration test (when running multiple tests), since execution will always halt at the beginning of the Maven process (due to "suspend=y").

**Comment by khmarbaise** [comment]
Can you please take a look on the branch  issue-186 and read the docs as well and maybe give some feedback if this helps?
